### PR TITLE
PR for class - 2

### PR DESCRIPTION
**Pull request by fahimar**
Some Functional Component has practiced.

### CODE REVIEW

**Review by tajnur007 — COMMENTED** [review]
Good practice. But you missed the routing part. Would you like to add the practice related to routing into this PR or in another PR?

**Comment by fahimar** [comment]
I would like to add more.

**Comment by fahimar** [comment]
I want to create another PR.

**Review by tajnur007 — APPROVED** [review]
Good practice brother. PR Approved!

**Pull request merged**
