### PR TITLE
PR for class-3 (React)

### PR DESCRIPTION
**Pull request by fahimar**
Will practice

Styling in React
CSS-in-JS libraries (styled-components).
CSS framework ( Tailwind CSS)
CSS Modules and other styling approaches.
Higher-Order Components (HOCs)
Enhancing components with HOCs.
Hooks
Introduction to React Hooks.
Commonly used hooks (useState, useEffect, useContext, useReducer etc.).

React Router (Dynamic Routing)
Navigating between pages in a React app.
Fetching Data
Making API requests in React.
Handling data with state and props.

### CODE REVIEW

**Review by tajnur007 — COMMENTED** [review]
Hi @fahimar,
I think, there was more topic related to React Class-3. Will you want to add those practices in a separate PR or in this PR?

**Comment by fahimar** [comment]
I will add in this PR soon.

**Comment by tajnur007** [comment]
It is better to create PR after completing your practices. So, keep focus to finish the practice first and then create PR.

**Review by tajnur007 — APPROVED** [review]
PR Approved!

**Comment by fahimar** [comment]
Thanks boro bhai ,it means a lot. How should I practice for the upcoming days to do better?😄

**Pull request merged**
